### ISSUE TITLE
PLL's clear_bit function ?

### ISSUE THREAD

**Issue by Nic0w** [rp-rs/rp2040-pac#16]
Hi,

Having bought a Pi Pico recently and wanting to try my hand on bare-metal/embedded/low-level Rust, I've been toying with this crate for the last 3 weeks or so.

I've started from the pico-blink-rs example and then I built HALs for GPIOs, XOSC, PLLs and Clocks.
I got GPIOs to work fine. I then put my focus on PLLs, my end goal being to setup clocks in order to setup UART.

To do that I replicated in Rust, using this crate, all the steps outlined in the official C code from the pico-sdk.

For the last week or so now I've been scratching my head because PLLs wouldn't work at all.
In order to debug I built a 7-Leds array with a Serial-to-Parallel shift register to display some values as binary. Thanks to bit shifting and a small delay I can display values 7 bits by 7 bits. The 8th LED is used as status LED.
I started debugging frequencies first with the Frequency Counter, and that would show 0Hz for my otherwise, in theory (reading the code) well configured PLL. 
Then I started debugging values for divders (refdiv, fbdiv, post div 1, post div 2); all of whom have correct values.
I went on with the PWR register, showing 1s in the wrong places, despite this code being written and called :+1: ``

```rust
        // Turn on self.device
        self.device.pwr.write(|w| unsafe {
            w.pd().clear_bit();
            w.vcopd().clear_bit();
            w
        });
        /* .... */
        self.device.pwr.write(|w| unsafe {
            w.postdivpd().clear_bit();
            w
        });
```
I then replaced those `clear_bit()` calls with a blanket `w.bits(0)` and suddenly my PLL turned on, showing a nominal 125Mhz.
So, either I'm wrong to think that clear_bit() is supposed to set a bit to 0, or it does not work... or something else is wrong.
I now wonder if my struggle with clocks isn't also linked to the same kind of issue.

Any thoughts ?

**Comment by 9names** [comment]
When you use .write() to write to a register, it starts with register's reset value, not 0.
Does the bit field you're seeing match this?
https://github.com/rp-rs/rp2040-pac/blob/f4339cb856f082970767099a0079259f333cdc7e/src/pll_sys/pwr.rs#L10

Most of the time I use the .modify() method as the goal is to alter the current value for the register.
If you definitely want a very specific bit pattern and do not care about the existing/reset value, using w.bits(0) as a base or explicitly setting every field through the accessors is a normal thing to do.

**Comment by Nic0w** [comment]
Hi,

Picking this up only now, sorry for the delay ! The value I'm seeing is 0x25, not 0x2D; ie `0b100101` :
- PD is set to 1
- DSMPD is set to 1
- VCOPD is set to 1

If I understand correctly what you're explaining, after my first write the register's value should be `0b001100`.
Then after the second write, starting from 0x2D and not the current value, it should indeed be `0b100101` ie 0x25.

So... no bug but a misunderstanding on my part on how `write()` works :/
I'm going to double-check all my code then and use modify instead !

**Comment by Nic0w** [comment]
I tested with `modify()` and the code works as expected ! Thanks again for the explanation =)
