### ISSUE TITLE
Spinlock registers are read-only

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp2040-pac#18]
In reference manual section 2.3.1.7, they describe SPINLOCK0-31 as being read only.
But, in the description (page 60), they state:
```
Reading from a spinlock address will:
- Return 0 if lock is already locked
- Otherwise return nonzero, and simultaneously claim the lock
Writing (any value) releases the lock.
```
So they're not really read-only registers - they are read-write!
We should patch the SVD to reflect this.

**Comment by Szpadel** [comment]
Can you also open issue upstream?

**Comment by 9names** [comment]
Done
https://github.com/raspberrypi/pico-sdk/issues/454
