### ISSUE TITLE
Rebuild from new svd

### ISSUE THREAD

**Issue by Szpadel** [rp-rs/rp2040-pac#19]
There is new pico sdk release, and it contains important changes (eg. required for usb support)

https://github.com/raspberrypi/pico-sdk/commit/0e95cbd25713a72d173f29ddaa7ead69deee0e87

Can we rebuild files basing on new svd?
Also this repository contains patched off sync patched version that is used for generation, can we maybe maintain instead .patch file or script for patching, so anyone could repatch it from original svd file?
Or if that is too complex or just too temporary, could we at least document changes that are needed.

thanks

**Comment by 9names** [comment]
> Also this repository contains patched off sync patched version that is used for generation, can we maybe maintain instead .patch file or script for patching, so anyone could repatch it from original svd file?

That what we're doing right now. If you run [update.sh](https://github.com/rp-rs/rp2040-pac/blob/main/update.sh) from the root of this repo, it runs svdtools to generate the patched svd.
The patch we apply to the svd is in svdtools format: [svd/rp2040.yaml](https://github.com/rp-rs/rp2040-pac/blob/main/svd/rp2040.yaml)

**Comment by Szpadel** [comment]
Thanks, I have no experience with svd, therefore I din't understood update process in script.

I created PR #20 new svd
