### ISSUE TITLE
Please List Some Examples On Readme.MD

### ISSUE THREAD

**Issue by DawnMagnet** [rp-rs/rp2040-pac#50]
Please List Some Examples On Readme.MD, Or It's too difficult for everyone to use

**Comment by Szpadel** [comment]
If you don't know how to use this library, you probably shouldn't.

Most likely you want to use [rp-hal](https://github.com/rp-rs/rp-hal).

PACs are mostly (>99% of the cases) used for developing HALs and not meant to be used directly.

**Comment by DawnMagnet** [comment]
Thanks！
