### ISSUE TITLE
Publish latest changes

### ISSUE THREAD

**Issue by ptpaterson** [rp-rs/rp2040-pac#65]
There have been some useful PRs since 0.3.0 release. In particular, I want access to the software interrupts. I'm using a local version of `rp2040_hal` to specify the latest pac from Github as dependency.

Can we bump the version to `0.3.1` and publish? I can work on a PR, but I don't know if there is a game plan.

Thanks!

**Comment by 9names** [comment]
Sorry about the long interval between PAC releases, we usually try to push them out more often when there are no breaking changes - this time there were some though.
Release 0.4.0 was just published, should be good to go.

**Comment by ptpaterson** [comment]
That was fantastic turnaround!!! Thanks a lot @9names and @jannic for the work. This project is awesome.
